### ISSUE TITLE
Spaces are not preserved

### ISSUE THREAD

**Issue by HendrikF** [ppati000/jodelstats#4]
Post like
```html
<p>.
<br />               .
<br />                    .
<br />                         .
<br />                                             .
<br />                        .
<br />                                     .
<br />#Sternenhimmel</p>
```
should not look like
```
.
.
.
.
.
.
#Sternenhimmel
```

Unfortunately I don't know ruby, but the responsible code might be
https://github.com/ppati000/jodelstats/blob/master/app/views/jodel_city/_jodel_post.html.erb#L11

**Comment by HendrikF** [comment]
A possible solution could be to add a new css-class with `white-space: pre-wrap`.

**Comment by patrick-petrovic** [comment]
Thanks a lot, wrapping everything into a <p> with `white-space: pre-wrap` did the trick.
